#!/bin/zsh
# DDS Domain Bootstrap — initialize the first node and enroll this machine.
#
# Run after installing the DDS Platform package:
#   sudo dds-bootstrap-domain
#
# This script:
#   1. Creates a new DDS domain (domain.toml + domain_key.bin)
#   2. Generates the node's P2P identity
#   3. Self-admits this node into the domain
#   4. Writes dds.toml configuration
#   5. Starts the dds-node LaunchDaemon
#   6. Enrolls this Mac as a device
#   7. Starts the policy agent
#
# After this, run: sudo dds-enroll-admin
set -euo pipefail

DDS_ROOT="/Library/Application Support/DDS"
NODE_DATA="${DDS_ROOT}/node-data"
NODE_BIN="/usr/local/bin/dds-node"
DDS_CLI="/usr/local/bin/dds"
API_URL="http://127.0.0.1:5551"

# ---- Preflight ----
if [[ $EUID -ne 0 ]]; then
  echo "Error: run with sudo" >&2
  exit 1
fi

[[ -x "${NODE_BIN}" ]] || { echo "Error: dds-node not found at ${NODE_BIN}" >&2; exit 1; }

if [[ -f "${NODE_DATA}/domain.toml" ]]; then
  echo "Domain already bootstrapped (${NODE_DATA}/domain.toml exists)."
  echo "To re-bootstrap, remove ${NODE_DATA} and re-run."
  exit 1
fi

echo ""
echo "=== DDS Domain Bootstrap ==="
echo ""

# ---- Collect inputs ----
printf "Domain name (e.g., acme.corp): "
read DOMAIN_NAME
[[ -n "${DOMAIN_NAME}" ]] || { echo "Domain name required" >&2; exit 1; }

printf "Organization hash (short ID, e.g., acme): "
read ORG_HASH
[[ -n "${ORG_HASH}" ]] || { echo "Org hash required" >&2; exit 1; }

printf "Protect domain key with FIDO2 hardware key? [Y/n]: "
read USE_FIDO2
USE_FIDO2="${USE_FIDO2:-Y}"

DOMAIN_PASSPHRASE=""
FIDO2_FLAG=""
if [[ "${USE_FIDO2}" =~ ^[Yy] ]]; then
  FIDO2_FLAG="--fido2"
  echo "  Domain key will be protected by your FIDO2 hardware key."
  echo "  You will need to touch the key twice during creation."
else
  printf "Domain key passphrase (protects the domain secret key): "
  read -s DOMAIN_PASSPHRASE
  echo ""
  [[ -n "${DOMAIN_PASSPHRASE}" ]] || { echo "Passphrase required" >&2; exit 1; }
fi

echo ""
echo "[1/7] Creating domain '${DOMAIN_NAME}'..."
mkdir -p "${NODE_DATA}"
if [[ -n "${DOMAIN_PASSPHRASE}" ]]; then
  export DDS_DOMAIN_PASSPHRASE="${DOMAIN_PASSPHRASE}"
fi
"${NODE_BIN}" init-domain --name "${DOMAIN_NAME}" --dir "${NODE_DATA}" ${FIDO2_FLAG} | tee "${NODE_DATA}/init-domain.out"

# Create provision bundle for sibling nodes
echo "  Creating provision bundle..."
"${NODE_BIN}" create-provision-bundle \
  --dir "${NODE_DATA}" \
  --org "${ORG_HASH}" \
  --out "${DDS_ROOT}/provision.dds"
echo "  Bundle: ${DDS_ROOT}/provision.dds"

# Parse domain info from domain.toml
DOMAIN_ID="$(awk -F'= ' '/^id = / { gsub(/"/, "", $2); print $2 }' "${NODE_DATA}/domain.toml")"
DOMAIN_PUBKEY="$(awk -F'= ' '/^pubkey = / { gsub(/"/, "", $2); print $2 }' "${NODE_DATA}/domain.toml")"
echo "  domain_id: ${DOMAIN_ID}"

echo ""
echo "[2/7] Generating node P2P identity..."
export DDS_NODE_PASSPHRASE=""  # node key unencrypted for LaunchDaemon use
"${NODE_BIN}" gen-node-key --data-dir "${NODE_DATA}" | tee "${NODE_DATA}/gen-node-key.out"
PEER_ID="$(awk '/peer_id:/ { print $2 }' "${NODE_DATA}/gen-node-key.out" | tail -n 1)"
[[ -n "${PEER_ID}" ]] || { echo "Failed to determine peer_id" >&2; exit 1; }
echo "  peer_id: ${PEER_ID}"

echo ""
echo "[3/7] Self-admitting this node..."
"${NODE_BIN}" admit \
  --domain-key "${NODE_DATA}/domain_key.bin" \
  --domain "${NODE_DATA}/domain.toml" \
  --peer-id "${PEER_ID}" \
  --out "${NODE_DATA}/admission.cbor" \
  --ttl-days 3650

echo ""
echo "[4/7] Writing node configuration..."

cat > "${DDS_ROOT}/dds.toml" <<EOF
# DDS Node Configuration — generated by dds-bootstrap-domain
data_dir = "${NODE_DATA}"
org_hash = "${ORG_HASH}"
trusted_roots = []

[network]
listen_addr = "/ip4/0.0.0.0/tcp/4001"
bootstrap_peers = []
mdns_enabled = true
heartbeat_secs = 5
idle_timeout_secs = 60
api_addr = "127.0.0.1:5551"

[domain]
name = "${DOMAIN_NAME}"
id = "${DOMAIN_ID}"
pubkey = "${DOMAIN_PUBKEY}"
admission_path = "${NODE_DATA}/admission.cbor"
audit_log_enabled = false
EOF
echo "  Written: ${DDS_ROOT}/dds.toml"

echo ""
echo "[5/7] Starting dds-node..."
launchctl enable system/com.dds.node 2>/dev/null || true
launchctl bootstrap system /Library/LaunchDaemons/com.dds.node.plist 2>/dev/null || \
  launchctl kickstart -k system/com.dds.node 2>/dev/null || true

# Wait for node to become ready
printf "  Waiting for node..."
for i in {1..30}; do
  if curl -sf "${API_URL}/v1/status" > /dev/null 2>&1; then
    echo " ready!"
    break
  fi
  printf "."
  sleep 1
done
curl -sf "${API_URL}/v1/status" > /dev/null 2>&1 || { echo " FAILED (node not responding)" >&2; exit 1; }

echo ""
echo "[6/7] Enrolling this Mac as a device..."
HOSTNAME_VALUE="$(hostname)"
OS_VERSION="$(sw_vers -productVersion 2>/dev/null || echo 'unknown')"
DEVICE_ID="DDS-MACOS-$(hostname -s | tr '[:lower:]' '[:upper:]')"

ENROLL_RESP=$(curl -sf \
  -X POST "${API_URL}/v1/enroll/device" \
  -H 'Content-Type: application/json' \
  -d "{
    \"label\": \"$(hostname -s)\",
    \"device_id\": \"${DEVICE_ID}\",
    \"hostname\": \"${HOSTNAME_VALUE}\",
    \"os\": \"macOS\",
    \"os_version\": \"${OS_VERSION}\",
    \"tpm_ek_hash\": null,
    \"org_unit\": \"${ORG_HASH}\",
    \"tags\": [\"bootstrap-node\"]
  }")

DEVICE_URN="$(echo "${ENROLL_RESP}" | python3 -c 'import sys,json; print(json.load(sys.stdin)["urn"])')"
echo "  device_urn: ${DEVICE_URN}"

# Update agent config with device URN
if [[ -f "${DDS_ROOT}/appsettings.json" ]]; then
  python3 -c "
import json, sys
with open('${DDS_ROOT}/appsettings.json') as f: cfg = json.load(f)
cfg['DdsPolicyAgent']['DeviceUrn'] = '${DEVICE_URN}'
with open('${DDS_ROOT}/appsettings.json', 'w') as f: json.dump(cfg, f, indent=2)
"
  echo "  Updated appsettings.json with device URN"
fi

echo ""
echo "[7/7] Starting policy agent..."
launchctl enable system/com.dds.policyagent 2>/dev/null || true
launchctl bootstrap system /Library/LaunchDaemons/com.dds.policyagent.plist 2>/dev/null || true

echo ""
echo "============================================================"
echo "  DDS Domain Bootstrap Complete"
echo "============================================================"
echo ""
echo "  Domain:     ${DOMAIN_NAME}"
echo "  Domain ID:  ${DOMAIN_ID}"
echo "  Device URN: ${DEVICE_URN}"
echo "  Peer ID:    ${PEER_ID}"
echo ""
echo "  Domain key: ${NODE_DATA}/domain_key.bin (KEEP SAFE)"
echo "  Config:     ${DDS_ROOT}/dds.toml"
echo ""
echo "  Provision bundle: ${DDS_ROOT}/provision.dds"
echo ""
echo "  Next steps:"
echo "    1. Enroll an admin:  sudo dds-enroll-admin"
echo "    2. Add another node: copy provision.dds to USB, then on new machine:"
echo "       sudo dds-node provision /path/to/provision.dds"
echo ""
echo "  Nodes on the same LAN auto-discover each other via mDNS."
echo ""

# Save bootstrap info for other scripts
cat > "${DDS_ROOT}/bootstrap.env" <<EOF
DOMAIN_NAME=${DOMAIN_NAME}
DOMAIN_ID=${DOMAIN_ID}
DOMAIN_PUBKEY=${DOMAIN_PUBKEY}
ORG_HASH=${ORG_HASH}
DEVICE_URN=${DEVICE_URN}
PEER_ID=${PEER_ID}
EOF
