#!/usr/bin/env bash
# DDS Domain Bootstrap — initialize the first node and enroll this machine.
#
# Linux port of platform/macos/packaging/dds-bootstrap-domain.sh. Run
# after installing the dds-linux package:
#   sudo dds-bootstrap-domain
#
# This script:
#   1. Creates a new DDS domain (domain.toml + domain_key.bin)
#   2. Generates the node's P2P identity
#   3. Self-admits this node into the domain
#   4. Writes dds.toml configuration
#   5. Starts the dds-node systemd unit
#   6. Enrolls this machine as a device
#   7. Creates the .bootstrap sentinel so `dds-fido2 admin-setup` /
#      `dds admin setup` can bootstrap the first admin
#
# After this, run: sudo dds-enroll-admin
set -euo pipefail

DATA_DIR="/var/lib/dds"
NODE_DATA="${DATA_DIR}/node"
NODE_TOML="${DATA_DIR}/dds.toml"
NODE_BIN="/usr/bin/dds-node"
# **SC-2** — Local API talks UDS only.
API_SOCK="${DATA_DIR}/dds.sock"
API_URL="http://localhost"

# ---- Preflight ----
if [[ $EUID -ne 0 ]]; then
  echo "Error: run with sudo" >&2
  exit 1
fi

[[ -x "${NODE_BIN}" ]] || { echo "Error: dds-node not found at ${NODE_BIN}" >&2; exit 1; }

if [[ -f "${NODE_DATA}/domain.toml" ]]; then
  echo "Domain already bootstrapped (${NODE_DATA}/domain.toml exists)."
  echo "To re-bootstrap, remove ${NODE_DATA} and re-run."
  exit 1
fi

echo ""
echo "=== DDS Domain Bootstrap ==="
echo ""

# ---- Collect inputs ----
printf "Domain name (e.g., acme.corp): "
read -r DOMAIN_NAME
[[ -n "${DOMAIN_NAME}" ]] || { echo "Domain name required" >&2; exit 1; }

printf "Organization hash (short ID, e.g., acme): "
read -r ORG_HASH
[[ -n "${ORG_HASH}" ]] || { echo "Org hash required" >&2; exit 1; }

printf "Protect domain key with FIDO2 hardware key? [Y/n]: "
read -r USE_FIDO2
USE_FIDO2="${USE_FIDO2:-Y}"

DOMAIN_PASSPHRASE=""
FIDO2_FLAG=""
if [[ "${USE_FIDO2}" =~ ^[Yy] ]]; then
  FIDO2_FLAG="--fido2"
  echo "  Domain key will be protected by your FIDO2 hardware key."
  echo "  You will need to touch the key twice during creation."
else
  printf "Domain key passphrase (protects the domain secret key): "
  read -rs DOMAIN_PASSPHRASE
  echo ""
  [[ -n "${DOMAIN_PASSPHRASE}" ]] || { echo "Passphrase required" >&2; exit 1; }
fi

echo ""
echo "[1/7] Creating domain '${DOMAIN_NAME}'..."
mkdir -p "${NODE_DATA}"
if [[ -n "${DOMAIN_PASSPHRASE}" ]]; then
  export DDS_DOMAIN_PASSPHRASE="${DOMAIN_PASSPHRASE}"
fi
"${NODE_BIN}" init-domain --name "${DOMAIN_NAME}" --dir "${NODE_DATA}" ${FIDO2_FLAG} | tee "${NODE_DATA}/init-domain.out"

# Create provision bundle for sibling nodes
echo "  Creating provision bundle..."
"${NODE_BIN}" create-provision-bundle \
  --dir "${NODE_DATA}" \
  --org "${ORG_HASH}" \
  --out "${DATA_DIR}/provision.dds"
echo "  Bundle: ${DATA_DIR}/provision.dds"

# Parse domain info from domain.toml
DOMAIN_ID="$(awk -F'= ' '/^id = / { gsub(/"/, "", $2); print $2 }' "${NODE_DATA}/domain.toml")"
DOMAIN_PUBKEY="$(awk -F'= ' '/^pubkey = / { gsub(/"/, "", $2); print $2 }' "${NODE_DATA}/domain.toml")"
echo "  domain_id: ${DOMAIN_ID}"

echo ""
echo "[2/7] Generating node P2P identity..."
export DDS_NODE_PASSPHRASE=""  # node key unencrypted for systemd-service use
"${NODE_BIN}" gen-node-key --data-dir "${NODE_DATA}" | tee "${NODE_DATA}/gen-node-key.out"
PEER_ID="$(awk '/peer_id:/ { print $2 }' "${NODE_DATA}/gen-node-key.out" | tail -n 1)"
[[ -n "${PEER_ID}" ]] || { echo "Failed to determine peer_id" >&2; exit 1; }
echo "  peer_id: ${PEER_ID}"
# PQ-DEFAULT-2: capture this node's hybrid KEM pubkey so the self-admit
# cert lets peers encapsulate epoch-key releases to it. Without it,
# encrypted-gossip (enc-v3) peers can never deliver their epoch keys
# here and replication from this node's peers stays dark.
KEM_HEX="$(awk '/kem_pubkey_hex:/ { print $2 }' "${NODE_DATA}/gen-node-key.out" | tail -n 1)"
if [[ -n "${KEM_HEX}" ]]; then
  echo "  kem_pubkey: captured ($((${#KEM_HEX} / 2)) bytes)"
else
  echo "  WARN: gen-node-key printed no kem_pubkey_hex; self-admit cert will lack the KEM pubkey (node self-repairs it at first start)" >&2
fi

echo ""
echo "[3/7] Self-admitting this node..."
ADMIT_ARGS=(
  admit
  --domain-key "${NODE_DATA}/domain_key.bin"
  --domain "${NODE_DATA}/domain.toml"
  --peer-id "${PEER_ID}"
  --out "${NODE_DATA}/admission.cbor"
  --ttl-days 3650
)
[[ -n "${KEM_HEX}" ]] && ADMIT_ARGS+=(--kem-pubkey "${KEM_HEX}")
"${NODE_BIN}" "${ADMIT_ARGS[@]}"

echo ""
echo "[4/7] Writing node configuration..."
cat > "${NODE_TOML}" <<EOF
# DDS Node Configuration — generated by dds-bootstrap-domain
data_dir = "${NODE_DATA}"
org_hash = "${ORG_HASH}"
trusted_roots = []

[network]
listen_addr = "/ip4/0.0.0.0/tcp/4001"
bootstrap_peers = []
mdns_enabled = true
heartbeat_secs = 5
idle_timeout_secs = 60
api_addr = "unix:${API_SOCK}"

[network.api_auth]
trust_loopback_tcp_admin = false
strict_device_binding = true

[domain]
name = "${DOMAIN_NAME}"
id = "${DOMAIN_ID}"
pubkey = "${DOMAIN_PUBKEY}"
admission_path = "${NODE_DATA}/admission.cbor"
audit_log_enabled = false
EOF
echo "  Written: ${NODE_TOML}"

echo ""
echo "[5/7] Starting dds-node..."
systemctl daemon-reload
systemctl restart dds-node.service
# Admission watchdog (0c41536 port) — external backstop that restarts
# the node if peers stay connected-but-unadmitted for ~15 min. Enabled
# alongside the node; 5-minute cadence via the systemd timer.
systemctl enable --now dds-watchdog.timer 2>/dev/null || true

printf "  Waiting for node..."
for _ in $(seq 1 30); do
  if curl -sf --unix-socket "${API_SOCK}" "${API_URL}/v1/status" > /dev/null 2>&1; then
    echo " ready!"
    break
  fi
  printf "."
  sleep 1
done
curl -sf --unix-socket "${API_SOCK}" "${API_URL}/v1/status" > /dev/null 2>&1 || { echo " FAILED (node not responding)" >&2; exit 1; }

echo ""
echo "[6/7] Enrolling this machine as a device..."
HOSTNAME_VALUE="$(hostname)"
OS_VERSION="$(source /etc/os-release 2>/dev/null && echo "${PRETTY_NAME:-unknown}" || echo unknown)"
DEVICE_ID="DDS-LINUX-$(hostname -s | tr '[:lower:]' '[:upper:]')"

ENROLL_RESP=$(curl -sf --unix-socket "${API_SOCK}" \
  -X POST "${API_URL}/v1/enroll/device" \
  -H 'Content-Type: application/json' \
  -d "{
    \"label\": \"$(hostname -s)\",
    \"device_id\": \"${DEVICE_ID}\",
    \"hostname\": \"${HOSTNAME_VALUE}\",
    \"os\": \"Linux\",
    \"os_version\": \"${OS_VERSION}\",
    \"tpm_ek_hash\": null,
    \"org_unit\": \"${ORG_HASH}\",
    \"tags\": [\"bootstrap-node\"]
  }")

DEVICE_URN="$(echo "${ENROLL_RESP}" | python3 -c 'import sys,json; print(json.load(sys.stdin)["urn"])')"
echo "  device_urn: ${DEVICE_URN}"

# Stamp the policy agent config with device URN + pinned node pubkey, if
# present (mirrors macOS's appsettings.json stamp; Linux's is JSON too).
NODE_PUBKEY_B64="$(curl -sf --unix-socket "${API_SOCK}" \
  "${API_URL}/v1/node/info" \
  | python3 -c 'import sys,json; print(json.load(sys.stdin)["node_pubkey_b64"])')"
POLICY_AGENT_CFG="/etc/dds/policy-agent.json"
if [[ -n "${NODE_PUBKEY_B64}" && -f "${POLICY_AGENT_CFG}" ]]; then
  python3 -c "
import json
with open('${POLICY_AGENT_CFG}') as f: cfg = json.load(f)
cfg['DeviceUrn'] = '${DEVICE_URN}'
cfg['PinnedNodePubkeyB64'] = '${NODE_PUBKEY_B64}'
with open('${POLICY_AGENT_CFG}', 'w') as f:
    json.dump(cfg, f, indent=2)
    f.write('\n')
"
  echo "  Updated ${POLICY_AGENT_CFG} with device URN + pinned node pubkey"
  systemctl restart dds-policy-agent.service 2>/dev/null || true
else
  echo "  ${POLICY_AGENT_CFG} not present — copy the example from"
  echo "  /usr/share/doc/dds-linux/examples/policy-agent.json first if you want the policy agent."
fi

# dds-node's C-2 security gate refuses every POST /v1/admin/setup call
# until this out-of-band sentinel exists (blocks a local unprivileged
# process from self-enrolling as admin). It's checked live on each
# request, not cached at node startup, so creating it here — after the
# service is already running — is sufficient; no restart needed.
# Consumed (deleted) automatically the moment admin_setup succeeds.
echo ""
echo "[7/7] Marking ready for first-admin bootstrap..."
BOOTSTRAP_SENTINEL="${NODE_DATA}/.bootstrap"
touch "${BOOTSTRAP_SENTINEL}"
echo "  Bootstrap sentinel: ${BOOTSTRAP_SENTINEL}"

echo ""
echo "============================================================"
echo "  DDS Domain Bootstrap Complete"
echo "============================================================"
echo ""
echo "  Domain:     ${DOMAIN_NAME}"
echo "  Domain ID:  ${DOMAIN_ID}"
echo "  Device URN: ${DEVICE_URN}"
echo "  Peer ID:    ${PEER_ID}"
echo ""
echo "  Domain key: ${NODE_DATA}/domain_key.bin (KEEP SAFE)"
echo "  Config:     ${NODE_TOML}"
echo ""
echo "  Provision bundle: ${DATA_DIR}/provision.dds"
echo "  NOTE: this bundle was created before an admin exists, so nodes"
echo "        provisioned from it would start with an empty trust anchor."
echo "        'sudo dds-enroll-admin' re-creates it automatically with the"
echo "        admin seeded once Admin Setup completes; only distribute the"
echo "        bundle after that. (Manual equivalent, if ever needed:"
echo "        dds-node create-provision-bundle --dir \"${NODE_DATA}\" --org \"${ORG_HASH}\" --out \"${DATA_DIR}/provision.dds\" --config \"${DATA_DIR}/dds.toml\")"
echo ""
echo "  Next steps:"
echo "    1. Enroll an admin:  sudo dds-enroll-admin"
echo "    2. Add another node: copy provision.dds, then on new machine:"
echo "       sudo dds-node provision /path/to/provision.dds"
echo ""
echo "  Nodes on the same LAN auto-discover each other via mDNS."
echo ""

# Save bootstrap info for other scripts
cat > "${DATA_DIR}/bootstrap.env" <<EOF
DOMAIN_NAME=${DOMAIN_NAME}
DOMAIN_ID=${DOMAIN_ID}
DOMAIN_PUBKEY=${DOMAIN_PUBKEY}
ORG_HASH=${ORG_HASH}
DEVICE_URN=${DEVICE_URN}
PEER_ID=${PEER_ID}
EOF
