#pragma once

#include "build_number.h"

#define DDS_CREDENTIAL_PROVIDER_MAJOR_VERSION "1.0"
#define DDS_CREDENTIAL_PROVIDER_VERSION DDS_CREDENTIAL_PROVIDER_MAJOR_VERSION "." BUILD_NUMBER

// Numeric version for VERSIONINFO resource
#define DDS_CREDENTIAL_PROVIDER_VERSION_NUMERIC 1,0,BUILD_NUMBER_NUMERIC,0
